FROM ubuntu:20.04

#Install everything as root (BAD!)
RUN apt-get update && apt-get install -y \
	python3 \
	python3-pip \
	curl \
	wget \
	vim \
	netcat \
	nmap \
	telnet \
	git

# Install Python packages
COPY requirements.txt /app/
RUN pip3 install -r /app/requirements.txt

# Copy application
COPY app.py /app/
COPY .env /app/

#Secrets in image (BAD!)
# ENV variables

WORKDIR /app

# Running as root (BAD!)
CMD ["python3", "app.py"]

